### ISSUE TITLE
Does UML redefined operation work at all?

### ISSUE THREAD

**Issue by DoItWithASmile** [eclipse-uml2/uml2#9]
Hey,
I cannot get redefined operations to work and need some help.

What I have:
I have an UML (meta)model. It looks like this.

```
package Model
{
	// isAbstract: true
	class baseClass
	{
		// isAbstract: false
		// isQuery:    true
		operation opA : String {
			body: 'base'
		}
	}

	// isAbstract: false
	class secondClass : baseClass
	{
		// redefines: baseClass::opA
		operation opA : String {
			body: 'second'	
		}
	}
}
```

After that, I create an Ecore genmodel based on that UML model. And generate the Model code. (all done in the latest release of Eclipse)

However, the "ModelPackage.java" contains errors due to duplicated code.

```
[...]
/**
 * The operation id for the '<em>Op A</em>' operation.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 * @ordered
 */
int SECOND_CLASS___OP_A = ModelPackage.BASE_CLASS___OP_A;

/**
 * The operation id for the '<em>Op A</em>' operation.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 * @ordered
 */
int SECOND_CLASS___OP_A = ModelPackage.BASE_CLASS_OPERATION_COUNT + 0;
[...]
```

Furthermore, with every code generation, the 2nd block is added over and over again.

Debugging lead me to 2 places:
1. JET template
2. GenOperation class

I traced it to the following Jet template: org.eclipse.emf.codegen.ecore.templates.model.PackageClass.javajet
```
[...]
        <%for (GenOperation genOperation : genClass.getAllGenOperations(false)) {%>
          <%if (genClass.getOverrideGenOperation(genOperation) == null) {%>
	/**
	 * The operation id for the '<em><%=genOperation.getFormattedName()%></em>' operation.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	<%=publicStaticFinalFlag%>int <%=genClass.getOperationID(genOperation, false)%> = <%=genClass.getOperationValue(genOperation)%>;

          <%}%>
        <%}%>
[...]
```

Looking at the Jet template and debugging the code, method isOverrideOf of the GenOperation is important. It is called in org.eclipse.emf.codegen.ecore.genmodel.impl.GenClassImpl::getOverideGenOperation:
```
[...]
  public GenOperation getOverrideGenOperation(GenOperation genOperation)
  {
    List<GenOperation> allGenOperations = getAllGenOperations(false);
    int index = allGenOperations.indexOf(genOperation);
    if (index != -1)
    {
      for (int i = allGenOperations.size() - 1; i > index; --i)
      {
        GenOperation otherGenOperation = allGenOperations.get(i);
        if (otherGenOperation.isOverrideOf(this, genOperation))
        {
          return otherGenOperation;
        }
      }
    }
    return null;
  }
[...]
```

GenOperation::isOverrideOf is where it becomes tricky. There are 2 implementations:
1. org.eclipse.emf.codegen.ecore.genmodel.impl.GenOperationImpl
2. org.eclipse.uml2.codegen.ecore.genmodel.impl.GenOperationImpl

for 1, there is an actual implementation. It matches it by name, parameter count, parameter name and parameter type.
for 2, the method simply returns false. Always. No checks. Just false.

Issue seems to be: when a genmodel is based on an UML model, then the UML2 implementation of GenOperation is used.
This leads to always returning false in isOverrideOf.
This leads to always returning null in getOverrideGenOperation
This leads to the duplicated / not necessary code to generate in the Jet template, because baseClass:OpA as well as secondClass::OpA are both generated for secondClass.
Thus, redefined operations always create duplicated and non-compiling code in the xxxPackage.java file.

Also, in the actual class file, the OpA operation is not annotated with "override" at all. Just like it doesn't know it is overriding / redefining something...
... because it doesn't know when using the UML2 implementation.

Looking at the Ecore model the genmodel creates, the secondClass::OpA contains an "redefines" annotation with the correct baseClass:OpA target.

Am I missing something?
Is there an annotation or something I have to set for this to resolve?
Or is the implementation of isOverrideOf the culpit?

**Comment by DoItWithASmile** [comment]
instead of returning false, the EMF implementation could be used instead.

```
return false; // -> return super.isOverrideOf(genClass, genOperation);
```

This becomes a question about how strict the code should stick to UML specification. Only redefined operations are "correctly" modelled according to spec.
However, the EMF implementation uses basic assumptions like same name, parameters etc. to match redefined operations automatically. Nice cushion to fall back into because always modelling redefined operations is a pain to begin with. This is not correct according to UML spec though.

**Comment by khussey** [comment]
Thanks for the issue and contribution, @DoItWithASmile ! It's been some time since I've looked closely at the code generation implementation in UML2 but it _should_ produce the desired results when using the right generator (the one from UML2, not the EMF one) and options.

I'll make some time to revisit the code and review your contribution but in the meantime can you share which options you used when creating the generator model and generating the code?

**Comment by DoItWithASmile** [comment]
Tools:
- latest Papyrus Eclipse, version 2023-12 (v4.30, build 2024-01-12T10:40:28Z)
- EMF Core: v2.37
- UML2: v.2.50
- UML2 Code Gen: v2.5.2

Genmodel
- model importer: UML model
- settings:
![image](https://github.com/eclipse-uml2/uml2/assets/36856607/154a701a-7f88-4450-b8e4-6a34514b3758)

Basically: Process everything, except duplicated stuff, CamelCaseName, untyped propertiers.

**Comment by khussey** [comment]
Closing this issue since I have verified that code generation for redefined operations does in fact work if/when the necessary options are processed.
